source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LocalizedStoryboard_Example', :exclusive => true do
  pod "LocalizedStoryboard", :path => "../"
end

target 'LocalizedStoryboard_Tests', :exclusive => true do
  pod "LocalizedStoryboard", :path => "../"

    pod 'Quick', '~> 0.6.0'
    pod 'Nimble', '2.0.0-rc.3'
end
